### ISSUE TITLE
Fix Note Test for Travis CI

### ISSUE THREAD

**Issue by gbroques** [gbroques/cozmo-song-match#14]
The `Note` unit test on [Travis CI](https://travis-ci.org/) fails because there's no audio device on the server.

This will need to be fixed somehow.

```
ERROR: setUpClass (test_note.TestNote)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/gbroques/cozmo-song-match/test/test_note.py", line 11, in setUpClass
    Note.init_mixer()
  File "/home/travis/build/gbroques/cozmo-song-match/song_match/song/note.py", line 33, in init_mixer
    init(frequency=44100, size=-16, channels=1, buffer=1024)
pygame.error: No available audio device
----------------------------------------------------------------------
Ran 0 tests in 0.009s
FAILED (errors=1)
The command "python -m unittest discover test" exited with 1.
Done. Your build exited with 1.
```

**Comment by gbroques** [comment]
Closed with 12a0938
